### ISSUE TITLE
mac arm芯片不兼容JavaFX

### ISSUE THREAD

**Issue by sdfdfasd12** [HotBoy-java/PotatoTool#1]
5月 08, 2024 10:50:04 上午 com.sun.javafx.application.PlatformImpl startup
警告: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6d6a0534'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib: dlopen(/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib, 0x0001): tried: '/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (no such file), '/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib: dlopen(/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib, 0x0001): tried: '/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (no such file), '/Users/admin/.openjfx/cache/17.0.10/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2030)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(SourceFile:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(SourceFile:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(SourceFile:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(SourceFile:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(SourceFile:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(SourceFile:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at com.sun.prism.GraphicsPipeline.createPipeline(SourceFile:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(SourceFile:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(SourceFile:125)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib: dlopen(/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib, 0x0001): tried: '/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (no such file), '/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib: dlopen(/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib, 0x0001): tried: '/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (no such file), '/Users/admin/.openjfx/cache/17.0.10/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2030)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(SourceFile:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(SourceFile:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(SourceFile:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(SourceFile:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SourceFile:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.prism.sw.SWPipeline.<clinit>(SourceFile:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at com.sun.prism.GraphicsPipeline.createPipeline(SourceFile:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(SourceFile:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(SourceFile:125)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(SourceFile:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(SourceFile:253)
	at com.sun.javafx.tk.Toolkit.getToolkit(SourceFile:268)
	at com.sun.javafx.application.PlatformImpl.startup(SourceFile:291)
	at com.sun.javafx.application.PlatformImpl.startup(SourceFile:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(SourceFile:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(SourceFile:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(SourceFile:196)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(SourceFile:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(SourceFile:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(SourceFile:280)
	at com.sun.javafx.application.PlatformImpl.startup(SourceFile:291)
	at com.sun.javafx.application.PlatformImpl.startup(SourceFile:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(SourceFile:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(SourceFile:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(SourceFile:196)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by ak005469075** [comment]
兄弟java什么版本，我win10 java-17，可以启动

**Comment by ljy1058318852** [comment]
非常抱歉，目前发现在Mac上的M系列处理器的兼容性还有待改进。即使在1.8版本中能够运行，但涉及到反编译时可能会遇到问题。这种情况下建议您在虚拟机中使用。【已经计划在下一个版本中改进对M系列处理器的兼容性】

**Comment by niuTT** [comment]
下载javafx17 后使用  java --module-path ./javafx17/lib --add-modules ALL-MODULE-PATH -jar PotatoTool-1.1-jdk11+.jar  完美运行
