### ISSUE TITLE
Eclipse Temurin Open JDK 8 运行jdk8版本报错

### ISSUE THREAD

**Issue by aphason** [HotBoy-java/PotatoTool#5]
Win11 64bit + Eclipse Temurin Open JDK 8 运行jdk8版本报错

D:\tools>java -jar PotatoTool-1.1-jdk8.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.potato.potatotool.ToStart.main(SourceFile:21)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 13 more

**Comment by ljy1058318852** [comment]
这个报错应该是未找到jdk自带的javafx进行加载，但jdk8是自带javafx。
请检查当前jdk版本，确定是否为jdk8

**Comment by ljy1058318852** [comment]
如在32位/M2系列处理器等条件下的java可能存在组件缺失等情况，建议安装zulu版本java，地址：https://www.azul.com/downloads/#zulu
